server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/tasko_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true


jwt:
  token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhYXJvbkBtYWlsLnJ1In0.0x

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE


